#!/usr/bin/env python3

from PIL import Image, ImageDraw
import sys

im0 = Image.open(sys.argv[1])
im1 = Image.open(sys.argv[2])

region = (0, 0, 400, 500)
crop0 = im0.crop(region)
crop1 = im1.crop(region)

qr1 = (0, 0, 100, 125)
qr2 = (100, 125, 200, 250)
qr3 = (200, 250, 300, 375)
qr4 = (300, 375, 400, 500)

qr5 = (100, 0, 200, 125)
qr6 = (200, 0, 300, 125)
qr7 = (300, 0, 400, 125)

qr8 = (0, 125, 100, 125)
qr9 = (100, 125, 200, 125)
qr10 = (200, 125, 300, 125)
qr11 = (300, 125, 400, 125)

lain1 = crop0.crop(qr1)
lain2 = crop0.crop(qr2)
lain3 = crop0.crop(qr3)
lain4 = crop0.crop(qr4)

lain5 = crop0.crop(qr5)
lain6 = crop0.crop(qr6)
lain7 = crop0.crop(qr7)
lain8 = crop0.crop(qr8)

lain9 = crop0.crop(qr9)
lain10 = crop0.crop(qr10)
lain11 = crop0.crop(qr11)
#lain12 = crop0.crop(qr12)

#crop1.paste(lain1, qr1)
#crop1.paste(lain2, qr2)
#crop1.paste(lain3, qr3)
#crop1.paste(lain4, qr4)
#crop1.paste(lain5, qr5)
#crop1.paste(lain6, qr6)
crop1.paste(lain7, qr7)
#crop1.paste(lain8, qr8)
#crop1.paste(lain9, qr9)
#crop1.paste(lain10, qr10)
#crop1.paste(lain11, qr11)

crop1.show()
