#!/usr/bin/env python3

from PIL import Image, ImageDraw
import sys

im0 = Image.open(sys.argv[1])
im1 = Image.open(sys.argv[2])

region = (0, 0, 400, 500)
crop0 = im0.crop(region)
crop1 = im1.crop(region)

qr10 = (0, 0, 100, 125)
qr15 = (100, 125, 200, 250)
qr20 = (100, 0, 200, 125)
qr25 = (200, 0, 400, 250)
qr30 = (0, 125, 100, 250)
qr35 = (0, 250, 200, 500)
qr40 = (100, 125, 200, 250)
qr45 = (200, 250, 400, 500)
qr_half = (200, 250, 400, 500)

lain10 = crop0.crop(qr10)
lain20 = crop0.crop(qr20)
lain30 = crop0.crop(qr30)
lain40 = crop0.crop(qr40)
lain15 = crop0.crop(qr15)
lain25 = crop0.crop(qr25)
lain35 = crop0.crop(qr35)
lain45 = crop0.crop(qr45)
lain_half = crop0.crop(qr_half)

crop1.paste(lain40, qr10)
crop1.paste(lain40, qr20)
crop1.paste(lain40, qr30)
crop1.paste(lain40, qr40)
crop1.paste(lain15, qr15)
crop1.paste(lain25, qr25)
crop1.paste(lain35, qr35)
crop1.paste(lain45, qr45)
crop1.paste(lain_half, qr35)

crop1.show()
